# docker-composeのバージョンを指定
version: "3.9"

# db(Postgres),django_app(Django)のコンテナを作成
services:
  db:
    container_name: dp_postgres
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
  django_app:
    container_name: dp_django_app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    working_dir: /var/www/djangoapp
    volumes:
      - .:/var/www/
      - ./static:/static
    # 8000番ポートをNginx側が接続できるよう開く
    expose:
      - "8000"
    # シェルスクリプトを実行
    command: sh -c "chmod 755 /var/www/entrypoint.sh && /var/www/entrypoint.sh && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    depends_on:
      - db
  web:
    # コンテナ名をwebに指定
    container_name: dp_web
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/nginx/Dockerfile
    # ボリュームを指定
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./static:/static
    # ローカルの80番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "80:80"
    # 先にdjango_appを起動してからwebを起動する
    depends_on:
      - django_app
volumes:
  db_data:
  static:
