# docker-composeのバージョンを指定
version: "3.9"

# db(Postgres),django_app(Django)のコンテナを作成
services:
  db:
    # コンテナ名をpostgresに設定
    container_name: postgres
    # PostgreSQLのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/postgres/Dockerfile
    # M1チップでも動くように
    # Intel Macの場合あってもなくても動く
    platform: linux/x86_64
    # DBのボリュームを指定
    # ローカルの/data/dbをコンテナの/var/lib/postgresql/dataにマウントする
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
  django_app:
    # コンテナ名をdjango_appに設定
    container_name: django_app
    # DjangoのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/django/Dockerfile
    working_dir: /var/www/djangoapp
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/var/www/にマウントする
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - .:/var/www/
      - ./static:/static
    # ローカルの8000番ポートとコンテナの8000番ポートをつなぐ
    ports:
      - "8000:8000"
    # シェルスクリプトを実行
    command: python /var/www/djangoapp/manage.py runserver 0.0.0.0:8000 --insecure
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    # 先にdbを起動してからwebを起動する
    depends_on:
      - db
volumes:
  db_data:
  static:
